db:
  src:
    DRIVER: '{ODBC Driver 18 for SQL Server}'
    SERVER: '10.10.10.20'
    DATABASE: 'LabMaestro'
    UID: 'lm'
    PWD: 'ChevroN123$'
    Encrypt: 'no'
    TrustServerCertificate: 'yes'
  dst:
    DRIVER: '{ODBC Driver 18 for SQL Server}'
    Server: '.'
    Database: 'LabMaestroS'
    Trusted_Connection: 'yes'
    Encrypt: 'no'
    TrustServerCertificate: 'yes'
    MARS_Connection: 'no'
barriers:
  daily: 20_000_000
  vary: 5_00_000